language: node_js
node_js:
  - 13

branches:
  only:
    - master

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy dougfoiles/reverseproxy:v1

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend dougfoiles/udagram-frontend:v1

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed dougfoiles/udagram-api-feed:v1

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user dougfoiles/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dougfoiles/reverseproxy:v1
  - docker push dougfoiles/udagram-frontend:v1
  - docker push dougfoiles/udagram-api-feed:v1
  - docker push dougfoiles/udagram-api-user:v1
